pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
            steps {
                echo 'Installing dependencies for Microservice B'
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Microservice B') {
            steps {
                echo 'Running Microservice B'
                sh 'python app_b.py &'
            }
        }
    }
}