pipeline {
    agent any

    stages {
        stage('Install Dependencies') {
           dir('microservice-a') { 
            steps {
                echo 'Installing dependencies for Microservice A'
                sh 'pip install -r requirements.txt'
            }
           }
        }

        stage('Run Microservice A') {
           dir('microservice-a') { 
            steps {
                echo 'Running Microservice A'
                sh 'python app_a.py &'
            }
           }
        }
    }
}