pipeline {
    agent any

    stages {
        stage('Check Environment') {
            steps {
               dir('microservice-a') { 
                echo 'Checking Python and pip versions...'
                sh 'python3 --version'
                sh 'pip --version'
               }
            }
        }

        stage('Install Dependencies') {
            steps {
               dir('microservice-a') { 
                echo 'Installing dependencies for Microservice A'
                sh 'pip install -r requirements.txt'
               }
            }
        }

        stage('Run Microservice A') {
            steps {
               dir('microservice-a') { 
                echo 'Running Microservice A'
                sh 'python3 app_a.py &'
               }
            }
        }
    }
}